name = "Frame4DD"
uuid = "70a0cd9f-3d70-4b89-ad90-2d0d49bb6120"
authors = ["AML"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
PrecompileTools = "1"
julia = "1.6"
