name = "Khepri"
uuid = "59ceddad-2dad-55ad-af66-072f48a109d0"
authors = ["aptmcl <antonio.menezes.leitao@gmail.com>"]
version = "1.5.0"

[deps]
KhepriAutoCAD = "84eb9a3b-232b-4081-b917-cfea549d0d83"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
KhepriAutoCAD = "1.4"
Reexport = "1"
julia = "1.12"

[extras]
KhepriBase = "4cc0fe96-1163-46f3-ba32-de1e65d9548f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["KhepriBase", "Test"]
